[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C687C1B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91fa7c660cbb1a3077cf8bdaa62fad9e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C687C3010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91fa7c660cbb1a3077cf8bdaa62fad9e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C663E5050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91fa7c660cbb1a3077cf8bdaa62fad9e/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C6907E110>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91fa7c660cbb1a3077cf8bdaa62fad9e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C6907CD90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91fa7c660cbb1a3077cf8bdaa62fad9e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028C6907DA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/91fa7c660cbb1a3077cf8bdaa62fad9e